import { test } from '@substrate-system/tapzero'
// Test fixtures must run BEFORE other test modules import UserDO so
// the prototype patches are in place before any test body runs.
import './_test-fixtures.js'
import './sidebar-footer-refresh.js'
import './refresh-lifecycle.js'
import './updating-pill-lifecycle.js'
import './sync.js'
import './sync-cycle.js'
import './db-adapter.js'
import './server-lww.js'
import './feed-fetch-security.js'
import './feed-parser.js'
import './feed-create.js'
import './do-handlers.js'
import './fetch-full-endpoint.js'
import './item-route.js'
import './state-route.js'
import './state-auth-storage.js'
import './api-router.js'
import './rate-limit.js'
import './alarm.js'
import './poll-state.js'
import './server-headers.js'
import './autumn-billing.js'
import './email.js'
import './session-cookie.js'
import './feed-cache-column.js'
import './feed-cache-policy.js'
import './cached-images.js'
import './storage-usage.js'
import './content-storage.js'
import './cache-eviction.js'
import './image-cache.js'
import './do-migrations.js'
import './feed-cursor.js'
import './header-component.js'
import './feed-status.js'
import './fetch-updates-button.js'
import './feed-status-loader.js'
import './item-row.js'
import './sidebar-item.js'
import './view-switch-instant.js'
import './view-switch-stale-refresh.js'
import './view-switch-cache-invalidate.js'
import './sidebar-feed-counts.js'
import './dot.js'
import './pending-update-empty-state.js'
import './feed-reader-pending-updates.js'
import './settings-route.js'
import './feed-reader-cache-disclosure.js'
import './sqlite-worker.js'
import './local-first-opfs-persistence.js'
import './blurhash-consumer.js'

test('all done', () => {
    if (window) {
        // @ts-expect-error tests
        window.testsFinished = true
    }
})
